### PR TITLE
Switch from node-dogstatsd to hot-shots

### PR DESCRIPTION
**Pull request by kcroaker**
### Description
This change switches from [node-dogstatsd](https://www.npmjs.com/package/node-dogstatsd) over to [hot-shots](https://www.npmjs.com/package/hot-shots).

### Motivation
**node-dogstatsd** has not been published for two years
**hot-shots** is actively maintained and was last published a month ago

### CODE REVIEW

**Comment by kcroaker** [comment]
@rochdev Can we get this pushed to npmjs as well? do you need me to do a version bump?

**Comment by rochdev** [comment]
I'll go through open issues and PRs tomorrow to see if there is anything else we can quickly include in the release first, but then I'll make another release.

**Comment by kcroaker** [comment]
👍

**Comment by rochdev** [comment]
Released in 0.0.9.

**Pull request merged**
